food2fork_key = 'd6ec9ede5565ccaf1417242d82d1f537'
food2fork_url = 'http://food2fork.com/api/search'
puppy_url = 'http://www.recipepuppy.com/api/'

yummly_id = 'fc171abd'
yummly_key = 'fa49e57cee213e565a01c0074e14ece2'
yummly_url = 'http://api.yummly.com/v1/api/recipes?'
yummly_recipe_url = 'https://www.yummly.com/#recipe/'

google_key = 'AIzaSyBrYWKNo4Pv3ZkRv0zYRK4i-ujnHi7nOpA'
search_url = 'https://maps.googleapis.com/maps/api/place/textsearch/json'
details_url = 'https://maps.googleapis.com/maps/api/place/details/json'
direction_url = 'https://maps.googleapis.com/maps/api/directions/json'
place_detail_url = 'https://maps.googleapis.com/maps/api/place/details/json'
photo_url = 'https://maps.googleapis.com/maps/api/place/photo'
map_url = 'https://maps.googleapis.com/maps/api/staticmap'
